import type { CandidateProfile } from './types'

export function buildProfileTextBlock(profile: CandidateProfile): string {
  return [
    `Full name: ${profile.fullName}`,
    `Email: ${profile.email}`,
    `Phone: ${profile.phone}`,
    `Country: ${profile.country}`,
    `City: ${profile.city}`,
    `Location: ${profile.location}`,
    `LinkedIn: ${profile.linkedin}`,
    `GitHub: ${profile.github}`,
    `Portfolio: ${profile.portfolio}`,
    `Twitter: ${profile.twitter}`,
    `Telegram: ${profile.telegram}`,
    `Current title: ${profile.currentTitle}`,
    `Current company: ${profile.currentCompany}`,
    `Years of experience: ${profile.yearsExperience}`,
    `Skills: ${profile.skills}`,
    `Languages: ${profile.languages}`,
    `Education:\n${profile.education}`,
    `Work experience:\n${profile.workExperience}`,
    `Bio / achievements: ${profile.bio}`,
    `Preferred salary: ${profile.preferredSalary || 'not specified'}`,
    `Notice period: ${profile.noticePeriod}`,
    `Work arrangement: ${profile.workArrangement}`,
    `Employment type: ${profile.employmentType}`,
    `Availability: ${profile.availability}`,
    `Timezone: ${profile.timezone}`,
    `Remote experience: ${profile.remoteExperience}`,
    `Work authorization: ${profile.workAuthorization}`,
    `Tax residency matches employer: ${profile.taxResidencyMatches}`,
    `Willing to relocate: ${profile.willingToRelocate}`,
    `Self-employed: ${profile.selfEmployed}`,
    `Home office: ${profile.homeOffice}`,
    `Async / distributed experience: ${profile.asyncExperience}`,
    `Referral source: ${profile.referralSource}`,
    `Cover letter tone: ${profile.coverLetterTone}`,
  ].join('\n')
}
